// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2nz07NAa8N-75Lz7ExoDa80JY7jDrU8',
    appId: '1:545894903810:android:b88bd9eb3cafd2a3b6b71b',
    messagingSenderId: '545894903810',
    projectId: 'orbaic-6832f',
    databaseURL: 'https://orbaic-6832f-default-rtdb.firebaseio.com',
    storageBucket: 'orbaic-6832f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSO4tb5zc1HviQkqj6eSn2AEAP3r8WMmQ',
    appId: '1:545894903810:ios:47ead991a8b1a034b6b71b',
    messagingSenderId: '545894903810',
    projectId: 'orbaic-6832f',
    databaseURL: 'https://orbaic-6832f-default-rtdb.firebaseio.com',
    storageBucket: 'orbaic-6832f.appspot.com',
    androidClientId: '545894903810-b2rthd7a4jsajeqdivbp94v3s0i20ls8.apps.googleusercontent.com',
    iosClientId: '545894903810-kh06i3hhpni563n23d9cm8e0e17ud8v6.apps.googleusercontent.com',
    iosBundleId: 'com.orbaic.miner',
  );

}